version: "3.8"

networks:
  default:
    name: loki

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: 10M
    max-file: 5
    tag: "{{.ImageName}}|{{.Name}}"

x-deploy:
  &default-deploy
  resources:
    limits:
      memory: 200M

services:
  app_python:
    image: staglente/app_python:latest
    ports:
      - "8000:5000"
    logging: *default-logging
    deploy: *default-deploy
    volumes:
      - ./app_data:/app_python/data

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging: *default-logging
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 15s
      timeout: 30s
      retries: 3

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    logging: *default-logging
    healthcheck:
      test: [ "CMD-SHELL", "ls -l /proc/*/exe | grep /promtail" ]
      interval: 30s
      timeout: 15s
      retries: 3

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    logging: *default-logging
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 30s
      timeout: 15s
      retries: 3

  prometheus:
    image: prom/prometheus:v2.45.4
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    logging: *default-logging
    deploy: *default-deploy
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/status || exit 1" ]
      start_period: 10s
      interval: 30s
      timeout: 15s
      retries: 5