spec:
   template:
      metadata:
        annotations:
          vault.hashicorp.com/agent-inject: 'true'
          vault.hashicorp.com/role: 'internal-app'
          vault.hashicorp.com/agent-inject-secret-server-config.txt: 'internal/data/server/config'