replicaCount: 1

image:
  repository: staglente/app_python
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  git: keep
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'internal-app'
  vault.hashicorp.com/agent-inject-secret-server-config.txt: 'internal/data/server/config'

podLabels: {}
podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts:
  - name: "visits"
    mountPath: "/data"
volumeClaim:
  name: "visits"
  storageSize: 20Mi
  accessModes: [ "ReadWriteOnce" ]

nodeSelector: {}
tolerations: []
affinity: {}